# Generated by Django 3.2.7 on 2021-09-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('ticker', models.CharField(default='NONE', max_length=5, primary_key=True, serialize=False, verbose_name='Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('transaction_date', models.DateTimeField(verbose_name='Date')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_coin_pair', to='portfolio.coin')),
                ('quote_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_coin_pair', to='portfolio.coin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.account')),
            ],
        ),
    ]
