# Generated by Django 3.2.7 on 2021-09-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('ticker', models.CharField(default='NONE', max_length=5, primary_key=True, serialize=False, verbose_name='Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('inserted_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.coin')),
            ],
        ),
    ]
