# Generated by Django 3.2.7 on 2021-09-26 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='base_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_coin_pair', to='portfolio.coin', verbose_name='Base Pair'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quote_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_coin_pair', to='portfolio.coin', verbose_name='Quote Pair'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Amount ($)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Fee ($)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, verbose_name='Transaction Type'),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
