# Generated by Django 3.2.7 on 2021-09-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_account_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='inserted_date',
            new_name='transaction_date',
        ),
    ]
